module.exports = [
    {
        city: "Manali",
        title: "Solang Valley",
        latitude: 32.3967,
        longitude: 77.3016,
        state: "Himachal Pradesh",
      },
      {
        city: "Rishikesh",
        title: "Camping by the Ganges",
        latitude: 30.0862,
        longitude: 78.2676,
        state: "Uttarakhand",
      },
      {
        city: "Nainital",
        title: "Pangot Camping",
        latitude: 29.3808,
        longitude: 79.4630,
        state: "Uttarakhand",
      },
      {
        city: "Shimla",
        title: "Mashobra Camping",
        latitude: 31.1241,
        longitude: 77.3325,
        state: "Himachal Pradesh",
      },
      {
        city: "Kasol",
        title: "Kheerganga Trek Base",
        latitude: 32.0099,
        longitude: 77.3156,
        state: "Himachal Pradesh",
      },
      {
        city: "Goa",
        title: "Palolem Beach",
        latitude: 15.0105,
        longitude: 74.0234,
        state: "Goa",
      },
      {
        city: "Leh",
        title: "Pangong Lake",
        latitude: 33.7734,
        longitude: 78.9345,
        state: "Ladakh",
      },
      {
        city: "Coorg",
        title: "Madikeri Camping",
        latitude: 12.4188,
        longitude: 75.7397,
        state: "Karnataka",
      },
      {
        city: "Auli",
        title: "Gurso Bugyal",
        latitude: 30.3256,
        longitude: 79.3802,
        state: "Uttarakhand",
      },
      {
        city: "Munnar",
        title: "Chokramudi Camping",
        latitude: 10.0889,
        longitude: 77.0595,
        state: "Kerala",
      },
      {
        city: "Darjeeling",
        title: "Tiger Hill",
        latitude: 27.0360,
        longitude: 88.2627,
        state: "West Bengal",
      },
      {
        city: "Ooty",
        title: "Doddabetta Peak",
        latitude: 11.4102,
        longitude: 76.6953,
        state: "Tamil Nadu",
      },
      {
        city: "Jaisalmer",
        title: "Sam Sand Dunes",
        latitude: 26.8530,
        longitude: 70.8833,
        state: "Rajasthan",
      },
      {
        city: "Pondicherry",
        title: "Paradise Beach",
        latitude: 11.9139,
        longitude: 79.8145,
        state: "Puducherry",
      },
      {
        city: "Dhanaulti",
        title: "Eco Park",
        latitude: 30.4490,
        longitude: 78.2263,
        state: "Uttarakhand",
      },
      {
        city: "Gulmarg",
        title: "Kongdoori Valley",
        latitude: 34.0489,
        longitude: 74.3834,
        state: "Jammu and Kashmir",
      },
      {
        city: "Kodaikanal",
        title: "Vattakanal Camping",
        latitude: 10.2381,
        longitude: 77.4892,
        state: "Tamil Nadu",
      },
      {
        city: "Yumthang Valley",
        title: "Yumthang Camping",
        latitude: 27.9546,
        longitude: 88.6930,
        state: "Sikkim",
      },
      {
        city: "Mount Abu",
        title: "Achalgarh Camping",
        latitude: 24.5917,
        longitude: 72.7156,
        state: "Rajasthan",
      },
      {
        city: "Rann of Kutch",
        title: "Dhordo Camping",
        latitude: 23.7337,
        longitude: 69.8597,
        state: "Gujarat",
      },
      {
        city: "Gangtok",
        title: "Tsomgo Lake",
        latitude: 27.3782,
        longitude: 88.6065,
        state: "Sikkim",
      },
      {
        city: "Chail",
        title: "Chail Wildlife",
        latitude: 30.9658,
        longitude: 76.7998,
        state: "Himachal Pradesh",
      },
      {
        city: "Wayanad",
        title: "Banasura Sagar",
        latitude: 11.6108,
        longitude: 75.9010,
        state: "Kerala",
      },
      {
        city: "Tarkarli",
        title: "Tarkarli Beach",
        latitude: 16.0067,
        longitude: 73.4628,
        state: "Maharashtra",
      },
      {
        city: "Kanatal",
        title: "Surkanda Devi",
        latitude: 30.4820,
        longitude: 78.3520,
        state: "Uttarakhand",
      },
      {
        city: "Dandeli",
        title: "Dandeli Wildlife",
        latitude: 15.2655,
        longitude: 74.6170,
        state: "Karnataka",
      },
      {
        city: "Hampi",
        title: "Hippie Island",
        latitude: 15.3350,
        longitude: 76.4600,
        state: "Karnataka",
      },
      {
        city: "Kausani",
        title: "Viewpoint Camping",
        latitude: 29.8507,
        longitude: 79.6044,
        state: "Uttarakhand",
      },
      {
        city: "Spiti Valley",
        title: "Chandratal Lake",
        latitude: 32.4174,
        longitude: 77.8182,
        state: "Himachal Pradesh",
      },
      {
        city: "Raipur",
        title: "Barnawapara Wildlife",
        latitude: 20.7873,
        longitude: 81.1524,
        state: "Chhattisgarh",
      },
      {
        city: "Jagdalpur",
        title: "Chitrakote",
        latitude: 18.8141,
        longitude: 81.4981,
        state: "Chhattisgarh",
      },
      {
        city: "Bilaspur",
        title: "Kanan Pendari",
        latitude: 22.0776,
        longitude: 82.1477,
        state: "Chhattisgarh",
      },
      {
        city: "Bhubaneswar",
        title: "Dhauligiri",
        latitude: 20.2627,
        longitude: 85.8328,
        state: "Odisha",
      },
      {
        city: "Puri",
        title: "Balukhand",
        latitude: 19.8134,
        longitude: 85.8315,
        state: "Odisha",
      },
      {
        city: "Cuttack",
        title: "Nandankanan",
        latitude: 20.3811,
        longitude: 85.8430,
        state: "Odisha",
      },
      {
        city: "Guwahati",
        title: "Kaziranga",
        latitude: 26.3962,
        longitude: 93.2663,
        state: "Assam",
      },
      {
        city: "Shillong",
        title: "Umiam Lake",
        latitude: 25.6769,
        longitude: 91.9501,
        state: "Meghalaya",
      },
      {
        city: "Aizawl",
        title: "Durtlang Hills",
        latitude: 23.7465,
        longitude: 92.7382,
        state: "Mizoram",
      },
      {
        city: "Kohima",
        title: "Dzukou Valley",
        latitude: 25.5070,
        longitude: 94.1076,
        state: "Nagaland",
      },
      {
        city: "Imphal",
        title: "Loktak Lake",
        latitude: 24.6715,
        longitude: 93.8812,
        state: "Manipur",
      },
      {
        city: "Agartala",
        title: "Neermahal Camping",
        latitude: 23.7871,
        longitude: 91.2800,
        state: "Tripura",
      },
      {
        city: "Itanagar",
        title: "Ziro Valley",
        latitude: 27.5575,
        longitude: 93.8287,
        state: "Arunachal Pradesh",
      },
      {
        city: "Aizawl",
        title: "Reiek Tlang",
        latitude: 23.7927,
        longitude: 92.8261,
        state: "Mizoram",
      },
      {
        city: "Shillong",
        title: "Mawlynnong",
        latitude: 25.0961,
        longitude: 91.5822,
        state: "Meghalaya",
      },
      {
        city: "Kohima",
        title: "Kisama Heritage",
        latitude: 25.6414,
        longitude: 94.1097,
        state: "Nagaland",
      },
      {
        city: "Gangtok",
        title: "Zero Point",
        latitude: 27.8486,
        longitude: 88.6414,
        state: "Sikkim",
      },
      {
        city: "Ooty",
        title: "Avalanche Lake",
        latitude: 11.4089,
        longitude: 76.6935,
        state: "Tamil Nadu",
      },
      {
        city: "Wayanad",
        title: "Chembra Peak",
        latitude: 11.5249,
        longitude: 76.0848,
        state: "Kerala",
      },
      {
        city: "Gokarna",
        title: "Kudle Beach",
        latitude: 14.5475,
        longitude: 74.3189,
        state: "Karnataka",
      },
      {
        city: "Hampi",
        title: "Hippie Island",
        latitude: 15.3350,
        longitude: 76.4600,
        state: "Karnataka",
      },
      {
        city: "Kodaikanal",
        title: "Manjalar Dam",
        latitude: 10.1815,
        longitude: 77.5385,
        state: "Tamil Nadu",
      },
      {
        city: "Gokarna",
        title: "Paradise Beach",
        latitude: 14.5475,
        longitude: 74.3189,
        state: "Karnataka",
      },
      {
        city: "Kanyakumari",
        title: "Vivekananda Rock",
        latitude: 8.0883,
        longitude: 77.5385,
        state: "Tamil Nadu",
      },
      {
        city: "Coonoor",
        title: "Lamb's Rock",
        latitude: 11.3287,
        longitude: 76.7947,
        state: "Tamil Nadu",
      },
      {
        city: "Kovalam",
        title: "Lighthouse Beach",
        latitude: 8.4022,
        longitude: 76.9780,
        state: "Kerala",
      },
      {
        city: "Agumbe",
        title: "Onake Abbi Falls",
        latitude: 13.4973,
        longitude: 75.0906,
        state: "Karnataka",
      },
      {
        city: "Varkala",
        title: "Varkala Beach",
        latitude: 8.7350,
        longitude: 76.7034,
        state: "Kerala",
      },
      {
        city: "Yercaud",
        title: "Pagoda Point",
        latitude: 11.7804,
        longitude: 78.2120,
        state: "Tamil Nadu",
      },
      {
        city: "Badami",
        title: "Badami Caves",
        latitude: 15.9186,
        longitude: 75.6761,
        state: "Karnataka",
      },
      {
        city: "Alleppey",
        title: "Alleppey Backwaters",
        latitude: 9.4981,
        longitude: 76.3388,
        state: "Kerala",
      }
]

                                                                 